autoscaler:
  image:
    repository: ghcr.io/keyval-dev/odigos/autoscaler
    tag: v0.0.7

scheduler:
  image:
    repository: ghcr.io/keyval-dev/odigos/scheduler
    tag: v0.0.7

langDetector:
  image:
    repository: ghcr.io/keyval-dev/odigos/lang-detector
    tag: v0.0.7

ui:
  image:
    repository: ghcr.io/keyval-dev/odigos/ui
    tag: v0.0.7

instrumentor:
  deleteLangDetectionPods: true
  image:
    repository: ghcr.io/keyval-dev/odigos/instrumentor
    tag: v0.0.7

