autoscaler:
  image:
    repository: ghcr.io/keyval-dev/odigos/autoscaler
    tag: v0.1.2

scheduler:
  image:
    repository: ghcr.io/keyval-dev/odigos/scheduler
    tag: v0.1.2

langDetector:
  image:
    repository: ghcr.io/keyval-dev/odigos/lang-detector
    tag: v0.1.2

ui:
  image:
    repository: ghcr.io/keyval-dev/odigos/ui
    tag: v0.1.2

instrumentor:
  deleteLangDetectionPods: true
  image:
    repository: ghcr.io/keyval-dev/odigos/instrumentor
    tag: v0.1.2

