apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odigos-scheduler
rules:
  - apiGroups:
      - odigos.io
    resources:
      - collectors
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - odigos.io
    resources:
      - collectors/finalizers
    verbs:
      - update
  - apiGroups:
      - odigos.io
    resources:
      - collectors/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - odigos.io
    resources:
      - instrumentedapplications
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - odigos.io
    resources:
      - instrumentedapplications/finalizers
    verbs:
      - update
  - apiGroups:
      - odigos.io
    resources:
      - instrumentedapplications/status
    verbs:
      - get
      - patch
      - update
